version: '3'
services:
  postgres:
    image: postgres
    environment:
      POSTGRES_PASSWORD: root
      POSTGRES_DB: projetointegrador
    volumes:
      - "./.postgres:/var/lib/postgresql/data"
    ports:
      - "5432:5432"
